# Optimising water delivery under constraints

The problem of water allocation can be mathematically described as a combinatorial optimisation problem. We model the system using a small number of water sources, including wells, desalination plants, or purchased water links. Each source is represented by a binary decision qubit indicating whether it is operational. Communities or demand regions can also be represented as qubits to track fulfillment of minimum water requirements. The objective is to maximise the total water delivered while respecting energy and sustainability constraints, which include limits on simultaneous plant operation, sustainable extraction thresholds, and minimum supply targets. These constraints are encoded as penalty terms in a QUBO or Hamiltonian formulation. This toy model illustrates how quantum optimisation can guide water distribution in resource-constrained environments, highlighting potential solutions for real-world sustainability challenges.

In [1]:
import pandas as pd
import random
import matplotlib.pyplot as plt

In [2]:
def graph(n=None):

    df = pd.read_csv(
        "cities_50largest.csv",
        sep=",",
        header=0,
        names=["city_id", "latitude", "longitude", "population_est"]
    )

    nodes = df[["city_id", "latitude", "longitude", "population_est"]]

    if n is not None:
        nodes = nodes[:n]

    random.seed(42)
    edge_prob = 0.5

    edges = []
    for i in range(len(nodes)):
        for j in range(i + 1, len(nodes)):
            if random.random() < edge_prob:
                u = int(nodes.iloc[i]["city_id"])
                v = int(nodes.iloc[j]["city_id"])
                weight = random.randint(1, 10)
                edges.append((u, v, weight))

    edges_df = pd.DataFrame(edges, columns=["from_city", "to_city", "weight"])

    return nodes, edges_df

In [ ]:
plt.figure(figsize=(8, 6))

coords = nodes.set_index("city_id")[["longitude", "latitude"]]

for _, edge in edges.iterrows():
    x1, y1 = coords.loc[edge["from_city"]]
    x2, y2 = coords.loc[edge["to_city"]]
    plt.plot([x1, x2], [y1, y2], color="gray", alpha=0.5, linewidth=1)

plt.scatter(
    nodes["longitude"],
    nodes["latitude"],
    s=nodes["population_est"] / 3000,
    color="tab:blue"
)

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Grafo de ciutats: longitud vs latitud amb edges")
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()

In [77]:
df = pd.read_csv(
    "main_cities.csv",
    sep=",",
    header=0,
    names=["city_id", "latitude", "longitude", "population_est"]
)

nodes = df[["city_id", "latitude", "longitude", "population_est"]]
nodes

    city_id  latitude  longitude  population_est
0         0    31.529     35.094          706508
1         1    31.768     35.213          419108
2         2    32.221     35.254          380961
3         3    31.900     35.204          348110
4         4    32.459     35.300          311231
5         5    31.705     35.203          216114
6         6    32.312     35.027          182053
7         7    32.190     34.971          110800
8         8    32.083     35.180           70727
9         9    32.322     35.369           64719
10       10    31.867     35.450           52154

In [78]:
random.seed(42)
edge_prob = 0.5

edges = []
for i in range(len(nodes)):
    for j in range(i + 1, len(nodes)):
        if random.random() < edge_prob:
            u = int(nodes.iloc[i]["city_id"])
            v = int(nodes.iloc[j]["city_id"])
            weight = random.randint(1, 10)
            edges.append((u, v, weight))

edges_df = pd.DataFrame(edges, columns=["from_city", "to_city", "weight"])
edges_df

    from_city  to_city  weight
0           0        2       5
1           0        3       3
2           0        7       7
3           0        8       2
4           0        9       9
5           1        5       8
6           1        8       3
7           1       10       3
8           2        3       6
9           2        4       7
10          2        5       6
11          3        4       9
12          3        5      10
13          3        7       4
14          3        9       4
15          4        8       8
16          4       10       6
17          5        6       5
18          5        9       3
19          6        7       8
20          6        8       9
21          6        9       6
22          7        9       1
23          8        9       2
24          8       10      10

In [3]:
nodes, edges = graph(11)

plt.figure(figsize=(8, 6))

coords = df.set_index("city_id")[["longitude", "latitude"]]
for _, edge in edges.iterrows():
    x1, y1 = coords.loc[edge["from_city"]]
    x2, y2 = coords.loc[edge["to_city"]]
    plt.plot([x1, x2], [y1, y2], color="gray", alpha=0.5, linewidth=1)

plt.scatter(
    df["longitude"],
    df["latitude"],
    s=df["population_est"] / 3000
)

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Latitude vs Longitude")
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()

NameError: name 'df' is not defined